export default {
  Guilds: 0,
  GuildMembers: 1,
  GuildModeration: 2,
  GuildEmojisAndStickers: 3,
  GuildIntegrations: 4,
  GuildWebhooks: 5,
  GuildInvites: 6,
  GuildVoiceStates: 7,
  GuildPresences: 8,
  GuildMessages: 9,
  GuildMessageReactions: 10,
  GuildMessageTyping: 11,
  DirectMessages: 12,
  DirectMessageReactions: 13,
  DirectMessageTyping: 14,
  MessageContent: 15,
  GuildScheduledEvents: 16,
  AutoModerationConfiguration: 20,
  AutoModerationExecution: 21,
};